name: Default JS Linter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env: 
        bot_name: ${{ secrets.BOT_NAME }}
        bot_email: ${{ secrets.BOT_EMAIL }}
        bot_password: ${{ secrets.BOT_PASSWORD }}
    - name: npm install, build, and test and lint
      run: |
        npm install
        npm run build --if-present
        npm test
        npm run format
        echo $bot_name
        git config --global user.email $bot_name
        git config --global user.name $bot_name
        git add .
        git commit -m "Linted Changes"
        git push
      env:
        CI: true
